# Generated by Django 2.1.7 on 2019-04-13 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
