# Generated by Django 2.1.7 on 2019-03-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mails_sent', models.IntegerField(default=0, editable=False)),
                ('visits', models.IntegerField(default=1, editable=False)),
                ('last_mail_sent', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
