# Generated by Django 2.1.7 on 2019-03-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='password',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='mails_sent',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='visit',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
